name: Diff Repo Trigger
on:
  push:

jobs:
  trigger-test2-job:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: cka-y/test2
          event-type: test1-push-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

